packages:
  - packages/*
  - apps/*
catalog:
  '@ai-sdk/openai': ^1.3.16
  '@ai-sdk/react': ^1.2.9
  '@ai-sdk/ui-utils': ^1.2.8
  '@antfu/eslint-config': ^4.12.0
  '@cloudflare/vite-plugin': ^1.0.8
  '@cloudflare/vitest-pool-workers': ^0.8.19
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@eslint-react/eslint-plugin': ^1.48.4
  '@fontsource-variable/geist': ^5.2.5
  '@fontsource-variable/nunito': ^5.2.5
  '@fontsource-variable/outfit': ^5.2.5
  '@fontsource-variable/unbounded': ^5.2.5
  '@hono/trpc-server': ^0.3.4
  '@hookform/resolvers': ^5.0.1
  '@libsql/client': ^0.15.4
  '@mantine/hooks': ^7.17.4
  '@openrouter/ai-sdk-provider': ^0.4.5
  '@radix-ui/react-accordion': ^1.2.8
  '@radix-ui/react-alert-dialog': ^1.1.11
  '@radix-ui/react-avatar': ^1.1.7
  '@radix-ui/react-checkbox': ^1.2.3
  '@radix-ui/react-collapsible': ^1.1.8
  '@radix-ui/react-context-menu': ^2.2.12
  '@radix-ui/react-dialog': ^1.1.11
  '@radix-ui/react-dropdown-menu': ^2.1.12
  '@radix-ui/react-label': ^2.1.4
  '@radix-ui/react-navigation-menu': ^1.2.10
  '@radix-ui/react-popover': ^1.1.11
  '@radix-ui/react-progress': ^1.1.4
  '@radix-ui/react-radio-group': ^1.3.4
  '@radix-ui/react-select': ^2.2.2
  '@radix-ui/react-separator': ^1.1.4
  '@radix-ui/react-slider': ^1.3.2
  '@radix-ui/react-slot': ^1.2.0
  '@radix-ui/react-switch': ^1.2.2
  '@radix-ui/react-tabs': ^1.1.9
  '@radix-ui/react-tooltip': ^1.2.4
  '@react-email/components': ^0.0.36
  '@react-router/dev': ^7.5.1
  '@t3-oss/env-core': ^0.12.0
  '@tailwindcss/postcss': ^4.1.4
  '@tailwindcss/vite': ^4.1.4
  '@tanstack/query-devtools': ^5.74.6
  '@tanstack/react-form': ^1.6.3
  '@tanstack/react-query': ^5.74.4
  '@tanstack/react-query-devtools': ^5.74.6
  '@tanstack/react-router': ^1.117.0
  '@tanstack/react-router-devtools': ^1.117.0
  '@tanstack/react-router-with-query': ^1.117.0
  '@tanstack/react-start': ^1.117.0
  '@tanstack/react-table': ^8.21.3
  '@tanstack/router-devtools': ^1.117.0
  '@tanstack/router-zod-adapter': ^1.81.5
  '@tanstack/start': ^1.117.0
  '@tanstack/zod-adapter': ^1.117.0
  '@trpc/client': ^11.1.1
  '@trpc/server': ^11.1.1
  '@trpc/tanstack-react-query': ^11.1.1
  '@types/node': ^22.14.1
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@upstash/ratelimit': ^2.0.5
  '@upstash/redis': ^1.34.8
  '@vercel/functions': ^2.0.0
  ai: ^4.3.9
  babel-plugin-react-compiler: 19.0.0-beta-e993439-20250405
  better-auth: ^1.2.7
  better-auth-harmony: ^1.2.4
  chalk: ^5.4.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  composio-core: ^0.5.33
  cross-env: ^7.0.3
  deepmerge: ^4.3.1
  dotenv: ^16.5.0
  drizzle-kit: ^0.31.0
  drizzle-orm: ^0.42.0
  eslint: ^9.25.1
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  fast-deep-equal: ^3.1.3
  hono: ^4.7.7
  husky: ^9.1.7
  input-otp: ^1.4.2
  isbot: 5.1.26
  lucide-react: ^0.487.0
  marked: ^15.0.9
  motion: ^12.7.4
  nanoid: ^5.1.5
  outdent: ^0.8.0
  react: 19.1.0
  react-dom: 19.1.0
  react-hook-form: ^7.56.1
  react-markdown: ^10.1.0
  react-router: ^7.5.1
  react-scan: ^0.3.3
  remark-gfm: ^4.0.1
  shiki: ^3.3.0
  sonner: ^2.0.3
  spin-delay: ^2.0.1
  superjson: ^2.2.2
  tailwind-merge: ^3.2.0
  tailwindcss: ^4.1.4
  tailwindcss-animate: ^1.0.7
  tsx: ^4.19.3
  turbo: ^2.5.0
  typescript: ^5.8.3
  usehooks-ts: ^3.1.1
  vinxi: 0.5.4
  vite: 6.3.2
  vite-env-only: ^3.0.3
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.2
  wrangler: ^4.13.0
  zod: ^3.24.3
