packages:
  - packages/*
  - apps/*
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@eslint-react/eslint-plugin': ^1.43.0
  '@types/node': ^22.14.1
  eslint: ^9.24.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  husky: ^9.1.7
  turbo: ^2.5.0
  typescript: ^5.8.3
